In [1]:
import numpy as np
a= np.array([5,5,5])
a

array([5, 5, 5])

In [2]:
type(a)

numpy.ndarray

In [3]:
len(a)

3

In [4]:
a[1]

np.int64(5)

In [5]:
a[0:]

array([5, 5, 5])

In [6]:
# list of lists
b = np.array([[5,5,5],[3,3,3,],[3,2,6,]])
b

array([[5, 5, 5],
       [3, 3, 3],
       [3, 2, 6]])

In [7]:
type(b)

numpy.ndarray

In [8]:
len(b)

3

In [9]:
b[0]

array([5, 5, 5])

In [10]:
b[0:]

array([[5, 5, 5],
       [3, 3, 3],
       [3, 2, 6]])

In [11]:
c=np.array([[3,3,3],[3,3,3]])
c

array([[3, 3, 3],
       [3, 3, 3]])

In [12]:
import numpy as np
a =np.array([1,2,3,4,6])
a

array([1, 2, 3, 4, 6])

In [13]:
b=np.zeros(2)
b

array([0., 0.])

In [14]:
c=np.ones(4)
c

array([1., 1., 1., 1.])

In [15]:
# empty array with 2 elements
d=np.empty(2)
d

array([0., 0.])

In [16]:
e =np.arange(5)
e

array([0, 1, 2, 3, 4])

In [17]:
# specific range of elements
f=np.arange(5,8)
f

array([5, 6, 7])

In [18]:
# continue....
g = np.arange(2,14,2)
g

array([ 2,  4,  6,  8, 10, 12])

In [19]:
# linearly spaced arrays
# it gives 5 numbers
h= np.linspace(0,10,num=5) 
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
# specific data types in an array
i = np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [21]:
j = np.ones(3,dtype=np.float64)
j

array([1., 1., 1.])

# 2 D Array

In [4]:
import numpy as np
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
import numpy as np
np.empty((3,4))

array([[1.20772868e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.20741561e-311, 8.75983079e+164, 5.58911347e-091,
        1.51168904e+160],
       [9.98730319e-048, 2.78605383e+179, 3.99910963e+252,
        1.20774417e-311]])

# 3-D Array

In [7]:
# making and reshaping a 3D array
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])